CREATE TABLE `orders` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `order_no` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务订单号（对外展示/对账），建议如 CP20260414XXXXXX',
  `user_id` bigint DEFAULT NULL,
  `amount` decimal(10,2) DEFAULT NULL,
  `credits` int DEFAULT NULL COMMENT '本单购买的积分数量（与 credit_buckets.granted_credits 一致）',
  `currency` varchar(10) COLLATE utf8mb4_general_ci DEFAULT 'USD',
  `product_sku` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '产品线标识，如 pack_50 / pack_120',
  `order_kind` varchar(32) COLLATE utf8mb4_general_ci DEFAULT 'credit_pack' COMMENT 'credit_pack | other',
  `status` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'pending | paid | failed | refunded | canceled | expired',
  `provider` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'creem | stripe_legacy 等',
  `provider_checkout_id` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Creem checkout / session id',
  `provider_payment_id` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '支付成功后的支付单号，用于退款 API',
  `provider_customer_id` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `refunded_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `user_id` (`user_id`),
  KEY `idx_user_created` (`user_id`,`created_at`),
  KEY `idx_provider_payment` (`provider`,`provider_payment_id`),
  CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='积分包等订单；按单退款与 credit_buckets.order_id 对应';